# Generated by Django 6.0.5 on 2026-05-21 01:20

import django.db.models.deletion
import gestion.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('n_cita', models.IntegerField(unique=True)),
                ('dia', models.DateField()),
                ('hora', models.TimeField(help_text='Hora de inicio de la cita')),
                ('duracion_minutos', models.PositiveIntegerField(default=30, help_text='Se hereda del servicio seleccionado')),
                ('hora_fin', models.TimeField(blank=True, editable=False, help_text='Calculado automáticamente', null=True)),
                ('monto_total', models.IntegerField(default=0)),
                ('divisa', models.CharField(default='CLP', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id_enfermedad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('n_servicio', models.IntegerField(help_text='Código correlativo del servicio', unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('monto', models.IntegerField()),
                ('divisa', models.CharField(default='CLP', max_length=3)),
                ('duracion_minutos', models.PositiveIntegerField(default=30, help_text='Duración estimada del procedimiento en minutos')),
            ],
        ),
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id_dueno', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rut', gestion.models.RutField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('fono', gestion.models.FonoField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_dueno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaCita',
            fields=[
                ('id_entrada_cita', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(help_text='Anotaciones de la consulta o receta médica')),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrada', to='gestion.cita')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id_feedback', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('n_estrellas', models.IntegerField()),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='gestion.cita')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('n_chip', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('edad', models.IntegerField()),
                ('fec_nac', models.DateField()),
                ('especie', models.CharField(max_length=50)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='gestion.dueno')),
                ('enfermedades', models.ManyToManyField(blank=True, related_name='mascotas', to='gestion.enfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id_ficha', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('n_ficha', models.IntegerField(unique=True)),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='gestion.mascota')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='gestion.mascota'),
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id_profesional', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rut', gestion.models.RutField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profesionales', to='gestion.cargo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profesional', to=settings.AUTH_USER_MODEL)),
                ('servicios', models.ManyToManyField(blank=True, help_text='Servicios/Especialidades que el profesional puede realizar', related_name='profesionales', to='gestion.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='gestion.profesional'),
        ),
        migrations.CreateModel(
            name='DetalleCita',
            fields=[
                ('id_detalle_cita', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto_total', models.IntegerField(help_text='Monto cobrado por este servicio específico en la cita')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.cita')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cita', to='gestion.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='servicios',
            field=models.ManyToManyField(related_name='citas', through='gestion.DetalleCita', to='gestion.servicio'),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('n_sucursal', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('servicios', models.ManyToManyField(blank=True, related_name='sucursales', to='gestion.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='profesional',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profesionales', to='gestion.sucursal'),
        ),
        migrations.AddField(
            model_name='cita',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='gestion.sucursal'),
        ),
        migrations.CreateModel(
            name='HorarioLaboral',
            fields=[
                ('id_horario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True, help_text='Permite desactivar un día feriado o libre rápidamente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='gestion.profesional')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='gestion.sucursal')),
            ],
            options={
                'unique_together': {('profesional', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
